// <auto-generated />
namespace DBLab2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RenameDishes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameDishes));
        
        string IMigrationMetadata.Id
        {
            get { return "202205151308311_RenameDishes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
